// Camera-compiler golden suite (task ving89w) — the pure TS port under
// src/lib/camera/ is loaded through the VM harness and asserted against
// fixtures generated BY the upstream Python source (bruxosdovfx Camera H3,
// v19.1 @ 846880d, Apache-2.0; see scripts/fixtures/camera-goldens.json
// _provenance and camera-goldens.py for regeneration). Sections:
//   (a) validate_path error taxonomy + option (_choice) errors — 27 + 6 rows
//   (b) interpolation parity — 9 series × 23 samples vs Python-computed
//       values within 1e-12 (pow is implementation-approximated per
//       ECMAScript — CPython uses libm; deltas are ≤ few ulps), plus
//       monotonicity/endpoint props
//   (c) golden prompts — 15 canonical cases: compiled_prompt, minimax_prompt,
//       info, storyboard_json and options compared BYTE-for-byte
//   (d) parity helpers — pyFloatRepr / pyFormatG / pyRound vs Python reprs
//   (e) camera vocabulary — end_view / parallax / aspect / fov / contracts
//   (f) diagnostics — review_path items + both language renderings
//   (g) loop closure — eligibility gates + the closure/motivos texts
//   (h) direction mirroring — 'invert H3 orbit' sign quirk, HUD path intact
//   (i) Motion Frame — <Video 1> rewrites, 17k+5 truncation, options
//       override, banner, forced-off closure
//   (j) coordinateAnchor — literal precision, defaults, error taxonomy
//
// Vitest port (task z7ogmig, 2026-09-20) of scripts/test-camera.cjs:
// assertion bodies carry over verbatim; the linear sections became one test
// each; the module-scope provenance assertion became its own leading test;
// the fixture stays in scripts/fixtures with an anchored path.
import { test } from 'vitest'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'

const require = createRequire(import.meta.url)
const __dirname = require('node:path').dirname(fileURLToPath(import.meta.url))

const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { loadTs } = require('../scripts/lib/ts-vm.cjs')

const FIXTURE = JSON.parse(fs.readFileSync(path.resolve(__dirname, '..', 'scripts', 'fixtures', 'camera-goldens.json'), 'utf8'))

let passed = 0
function ok(condition, label) {
  assert.ok(condition, label)
  passed += 1
  console.log(`  ok - ${label}`)
}
function eq(actual, expected, label) {
  // VM harness runs modules in their own realm — cross-realm arrays fail
  // deepStrictEqual on prototype identity; JSON normalization is the honest
  // comparison for plain data.
  assert.deepEqual(JSON.parse(JSON.stringify(actual)), JSON.parse(JSON.stringify(expected)), label)
  passed += 1
  console.log(`  ok - ${label}`)
}
function same(actual, expected, label) {
  assert.strictEqual(actual, expected, `${label}\n--- actual ---\n${String(actual).slice(0, 600)}\n--- expected ---\n${String(expected).slice(0, 600)}`)
  passed += 1
  console.log(`  ok - ${label}`)
}

const lib = loadTs('src/lib/camera/index.ts')
const parity = loadTs('src/lib/camera/parity.ts')
const semantics = loadTs('src/lib/engineSemantics.ts')

const PROVENANCE = FIXTURE._provenance

function shapeOf(ref) {
  return ref ? { shape: ref.shape } : null
}

function runCase(c) {
  const input = c.input
  if (c.driver === 'compile') {
    return lib.compileCamera({
      cameraTrajectory: input.raw,
      profile: input.profile,
      interpolation: input.interpolation,
      instruction: input.instruction,
      subjectFraming: input.framing,
      minimaxFormat: input.minimax_format,
      referenceImage: shapeOf(input.reference_image),
      elevationRange: input.elevation_range,
      orbitDirection: input.orbit_direction,
      subjectBox: input.subject_box,
      runtimeTask: input.runtime_task,
      promptDetail: input.prompt_detail,
      allowClosure: input.allow_closure,
    })
  }
  return lib.compileMotion({
    cameraTrajectory: input.camera_trajectory,
    profile: input.profile,
    interpolation: input.interpolation,
    instruction: input.instruction,
    subjectFraming: input.subject_framing,
    minimaxFormat: input.minimax_format,
    referenceImage: shapeOf(input.reference_image),
    elevationRange: input.elevation_range,
    orbitDirection: input.orbit_direction,
    subjectBox: input.subject_box,
    runtimeTask: input.runtime_task,
    promptDetail: input.prompt_detail,
    frameMode: input.frame_mode,
    sourceFps: input.source_fps,
    freezeIndex: input.freeze_index,
    uiLanguage: input.ui_language,
    loopClosure: input.loop_closure,
  })
}

test('fixture provenance pins the audited upstream commit', () => {
  same(PROVENANCE.source_commit, '846880de859959e801b2c506dc424bd5c8b5c6c4', 'fixture provenance pins the audited upstream commit')
})

test('(a) validate_path taxonomy', () => {
  for (const row of FIXTURE.validation) {
    if (row.error === null) {
      const parsed = lib.validatePath(row.raw)
      eq(parsed, row.path, `validation ${row.label}: accepted, floats coerced`)
    } else {
      assert.throws(() => lib.validatePath(row.raw), (err) => err.message === row.error,
        `validation ${row.label} message mismatch`)
      passed += 1
      console.log(`  ok - validation ${row.label}: "${row.error}"`)
    }
  }
  for (const row of FIXTURE.option_errors) {
    const attempt = () => lib.compileCamera({
      cameraTrajectory: JSON.stringify([
        { time: 0, azimuth: 0, elevation: 0, distance: 1 },
        { time: 1, azimuth: 90, elevation: 0, distance: 1 },
      ]),
      profile: row.label === 'unknown_profile' ? '99 frames' : '124 frames (~5.17s)',
      interpolation: row.label === 'unknown_interpolation' ? 'cubic' : 'smooth',
      instruction: '',
      orbitDirection: row.label === 'unknown_orbit' ? 'sideways'
        : row.label === 'empty_orbit_falls_back' ? '' : null,
      minimaxFormat: row.label === 'unknown_format' ? 'yaml'
        : row.label === 'none_format_falls_back' ? null : null,
    })
    if (row.error === null) {
      attempt() // must not throw — the fallback kicks in
      passed += 1
      console.log(`  ok - option ${row.label}: falls back to default without error`)
    } else {
      assert.throws(attempt, (err) => err.message === row.error, `option ${row.label} message mismatch`)
      passed += 1
      console.log(`  ok - option ${row.label}: "${row.error}"`)
    }
  }
})

test('(b) interpolation parity (monotone PCHIP / smoothstep / linear)', () => {
  // Numeric parity tolerance: pow() is implementation-approximated (see the
  // trajectoryMath note), so sampled poses compare within 1e-12 relative —
  // several orders above the observed ulp-level deltas, tight enough to
  // catch any real interpolation divergence.
  const CLOSE = (a, b) => Math.abs(a - b) <= 1e-12 * Math.max(1, Math.abs(a), Math.abs(b))
  for (const series of FIXTURE.interpolation) {
    const key = `${series.path}|${series.interpolation}|${series.detail}`
    for (const sample of series.samples) {
      const pose = lib.interpolatePose(
        pathFromName(series.path), sample.time,
        series.interpolation, series.detail,
      )
      assert.ok(CLOSE(pose.azimuth, sample.azimuth), `${key} t=${sample.time} azimuth`)
      assert.ok(CLOSE(pose.elevation, sample.elevation), `${key} t=${sample.time} elevation`)
      assert.ok(CLOSE(pose.distance, sample.distance), `${key} t=${sample.time} distance`)
    }
    passed += 1
    console.log(`  ok - ${key}: ${series.samples.length} samples within 1e-12 of Python`)
  }
  // Properties the golden table also implies, stated explicitly: the monotone
  // cubic stays within each segment's endpoint pair on every axis (the
  // upstream clamp is a no-op for exact math; this proves it holds).
  const slopePath = pathFromName('slope')
  let contained = true
  for (const sample of FIXTURE.slope_samples.samples) {
    const t = Math.min(Math.max(sample.time, 0), 1)
    let seg = 0
    while (seg < slopePath.length - 2 && t > slopePath[seg + 1].time) seg += 1
    const lo = slopePath[seg]
    const hi = slopePath[seg + 1]
    for (const axis of ['azimuth', 'elevation', 'distance']) {
      const low = Math.min(lo[axis], hi[axis])
      const high = Math.max(lo[axis], hi[axis])
      if (sample[axis] < low - 1e-9 || sample[axis] > high + 1e-9) contained = false
    }
  }
  ok(contained, 'PCHIP never overshoots its segment endpoints on the reversal path')
  for (const sample of FIXTURE.slope_samples.samples) {
    const pose = lib.interpolatePose(slopePath, sample.time, 'smooth', 'extended contracts')
    const closeSlope = (a, b) => Math.abs(a - b) <= 1e-12 * Math.max(1, Math.abs(a), Math.abs(b))
    assert.ok(closeSlope(pose.azimuth, sample.azimuth), `slope t=${sample.time} azimuth`)
    assert.ok(closeSlope(pose.elevation, sample.elevation), `slope t=${sample.time} elevation`)
    assert.ok(closeSlope(pose.distance, sample.distance), `slope t=${sample.time} distance`)
  }
  passed += 1
  console.log('  ok - slope stress path: 41 samples within 1e-12 of Python')
  for (const row of FIXTURE.interp_errors) {
    if (row.label !== 'nan_time') continue
    assert.throws(() => lib.interpolatePose(pathFromName('video_00063'), NaN, 'smooth', 'extended contracts'),
      (e) => e.message === row.error, 'nan time message')
    passed += 1
    console.log('  ok - interpolatePose rejects non-finite time with the bilingual message')
    break
  }
  assert.throws(() => lib.interpolatePose([], 0.5), (e) => e.message === 'Empty camera path / Trajetória vazia.')
  passed += 1
  console.log('  ok - interpolatePose rejects an empty path')
})

test('(c) golden prompts — byte-for-byte vs the upstream compiler', () => {
  for (const c of FIXTURE.cases) {
    const result = runCase(c)
    same(result.compiledPrompt, c.outputs.compiled_prompt, `${c.id}: compiled_prompt identical`)
    same(result.minimaxPrompt, c.outputs.minimax_prompt, `${c.id}: minimax_prompt identical`)
    same(result.info, c.outputs.info, `${c.id}: info banner identical`)
    same(result.storyboardJson, c.outputs.storyboard_json, `${c.id}: storyboard_json identical (floats, key order)`)
    same(parity.pyJsonStringify(result.options), c.outputs.options_json, `${c.id}: options identical`)
    assert.strictEqual(result.frames, c.outputs.frames, `${c.id}: frames`)
    assert.strictEqual(result.fps, c.outputs.fps, `${c.id}: fps`)
    passed += 2
    console.log(`  ok - ${c.id}: frames/fps match`)
  }
  // Six-section format structure on one representative compiled prompt.
  const sample = runCase(FIXTURE.cases[0]).compiledPrompt
  for (const section of ['subject_definitions:', 'summary:', 'retention_analysis:', 'detailed_description:', 'overall_soundscape:', 'non_diegetic_music:']) {
    ok(sample.includes(section), `six-section format carries "${section}"`)
  }
})

test('(d) Python parity helpers', () => {
  for (const row of FIXTURE.helpers.float_repr) {
    same(parity.pyFloatRepr(Number.parseFloat(row.label)), row.value, `pyFloatRepr(${row.label}) === ${row.value}`)
  }
  for (const row of FIXTURE.helpers.format_g) {
    same(parity.pyFormatG(Number.parseFloat(row.label)), row.value, `pyFormatG(${row.label}) === ${row.value}`)
  }
  for (const row of FIXTURE.helpers.round6) {
    same(parity.pyFloatRepr(parity.pyRound(Number.parseFloat(row.label), 6)), row.value, `pyRound(${row.label}, 6)`)
  }
  for (const row of FIXTURE.helpers.round3) {
    same(parity.pyFloatRepr(parity.pyRound(Number.parseFloat(row.label), 3)), row.value, `pyRound(${row.label}, 3)`)
  }
})

test('(e) camera vocabulary', () => {
  for (const row of FIXTURE.helpers.end_view) {
    same(lib.endView(row.net), row.text, `endView(${row.net})`)
  }
  for (const row of FIXTURE.helpers.parallax) {
    same(lib.parallaxTravel(row.daz, row.de, row.aspect), row.text, `parallaxTravel(${row.daz}, ${row.de}, ${row.aspect})`)
  }
  for (const row of FIXTURE.helpers.aspect_label) {
    same(lib.aspectLabel(row.aspect), row.label, `aspectLabel(${row.aspect})`)
  }
  for (const row of FIXTURE.helpers.horizontal_fov) {
    // atan/tan are implementation-approximated like pow — numeric parity
    // within 1e-12 (the parallax TEXT built from these values is compared
    // byte-exactly above and sits far from any rounding boundary).
    const fov = lib.horizontalFov(row.aspect)
    assert.ok(Math.abs(fov - row.fov) <= 1e-12 * Math.max(1, Math.abs(row.fov)), `horizontalFov(${row.aspect})`)
    passed += 1
    console.log(`  ok - horizontalFov(${row.aspect}) within 1e-12`)
  }
  for (const row of FIXTURE.helpers.direction_contract) {
    same(lib.directionContract(pathFromName(row.path)), row.text, `directionContract(${row.path})`)
  }
  for (const row of FIXTURE.helpers.image_aspect) {
    if (row.shape === 'no_shape') continue
    assert.strictEqual(lib.imageAspect({ shape: row.shape }), row.aspect, `imageAspect(${JSON.stringify(row.shape)})`)
    passed += 1
    console.log(`  ok - imageAspect(${JSON.stringify(row.shape)}) === ${row.aspect}`)
  }
  ok(lib.imageAspect(null) === null, 'imageAspect(null) is null')
})

test('(f) diagnostics', () => {
  for (const entry of FIXTURE.diagnostics) {
    const items = lib.reviewPath(pathFromName(entry.path), entry.duration, entry.elevation_limit)
    eq(items, entry.items, `reviewPath(${entry.path}) items identical`)
    same(lib.diagnosticText(items, true), entry.en_text, `diagnosticText(${entry.path}, en) identical`)
    same(lib.diagnosticText(items, false), entry.pt_text, `diagnosticText(${entry.path}, pt) identical`)
  }
})

test('(g) loop closure', () => {
  const loop = FIXTURE.cases.find((c) => c.id === 'freeze_loop360')
  const result = runCase(loop)
  ok(result.options.coverage_loop_closure === true, 'exact ±360 with elevation+distance return closes the loop')
  ok(result.compiledPrompt.includes('Reference alignment:'), 'closure prepends the <Picture 2> alignment instruction')
  const near = FIXTURE.cases.find((c) => c.id === 'node_freeze_loop355')
  const nearResult = runCase(near)
  ok(nearResult.options.coverage_loop_closure === false, '355° does not close the loop')
  ok(nearResult.info.includes('Loop closure OFF: giro 355°; exige 360°'), 'the node banner states the unmet 360 requirement')
  // The v16 compile-level info (not the node banner) quantifies the shortfall.
  const nearCompile = lib.compileCamera({
    cameraTrajectory: JSON.stringify([
      { time: 0, azimuth: 0, elevation: 0, distance: 1 },
      { time: 0.5, azimuth: 178, elevation: 5, distance: 1.1 },
      { time: 1, azimuth: 355, elevation: 0, distance: 1 },
    ]),
    profile: '124 frames (~5.17s)', interpolation: 'smooth', instruction: '',
    referenceImage: { shape: [1, 1080, 1920, 3] },
  })
  ok(nearCompile.info.includes('faltam 5.00 graus de giro'), 'the compile info quantifies the 5.00 missing degrees')
  // Elevation mismatch alone disqualifies.
  const noClose = lib.compileCamera({
    cameraTrajectory: JSON.stringify([
      { time: 0, azimuth: 0, elevation: 0, distance: 1 },
      { time: 1, azimuth: 360, elevation: 4, distance: 1 },
    ]),
    profile: '124 frames (~5.17s)', interpolation: 'smooth', instruction: '',
    referenceImage: { shape: [1, 1080, 1920, 3] },
  })
  ok(noClose.options.coverage_loop_closure === false, 'elevation not returning disqualifies closure')
  ok(noClose.info.includes('a elevacao termina em 4 em vez de 0'), 'elevation motivo is reported')
})

test('(h) direction mirroring quirk', () => {
  const right = FIXTURE.cases.find((c) => c.id === 'freeze_orbit90_v15')
  const result = runCase(right)
  ok(result.compiledPrompt.includes("toward the camera's LEFT"), 'default invert H3 orbit mirrors +90 to LEFT in the prompt')
  const storyboard = JSON.parse(result.storyboardJson)
  eq(storyboard.path[1].azimuth, 90, 'the saved HUD path keeps the authored +90')
  eq(storyboard.model_path[1].azimuth, -90, 'the model path carries the mirrored -90')
  const sameHud = FIXTURE.cases.find((c) => c.id === 'node_freeze_samehud_en')
  const sameHudResult = runCase(sameHud)
  ok(sameHudResult.compiledPrompt.includes("toward the camera's RIGHT"), "'same as HUD' keeps the authored direction")
  const loopResult = runCase(FIXTURE.cases.find((c) => c.id === 'freeze_loop360'))
  ok(loopResult.options.coverage_direction === 'counterclockwise / camera left', 'mirroring flips coverage_direction for a +360 authored circle')
})

test('(i) Motion Frame semantics', () => {
  const motion = FIXTURE.cases.find((c) => c.id === 'node_motion_multikey')
  const result = runCase(motion)
  ok(result.compiledPrompt.includes('<Video 1> is the temporal action reference.'), '<Picture 1> headline becomes <Video 1>')
  ok(!result.compiledPrompt.includes('<Picture 1> is the exact reference first frame.'), 'no <Picture 1> headline remains')
  ok(result.compiledPrompt.includes('the subject continues its source action'), 'stationary-subject clause rewritten to action continuation')
  ok(result.compiledPrompt.includes('tracked subject target'), 'fixed-target orbit clauses become tracked-subject')
  eq(result.options, { coverage_loop_closure: false, bruxosdovfx_requires_ref2va: true }, 'options replaced by the Ref2VA requirement marker')
  ok(result.info.includes('Loop closure OFF: a ação continua'), 'closure forced off with the action-continues reason')
  ok(result.info.includes('61 / 107'), 'banner reports the 17k+5-truncated reference count (61/107)')
  eq(result.resample.indices, FIXTURE.resample.find((r) => r.count === 61 && r.indices).indices, 'resample indices identical')
  assert.strictEqual(result.resample.target, 122, 'target before grid truncation')
  assert.strictEqual(result.resample.aligned, 107, 'aligned = 5+17*6')
  // 17k+5 semantics table.
  for (const row of FIXTURE.resample) {
    if (row.mode) continue
    if (row.error) {
      assert.throws(() => lib.motionFrameResample(row.count, row.source_fps), (err) => err.message === row.error,
        `motionFrameResample(${row.count}@${row.source_fps}) error mismatch`)
      passed += 1
      console.log(`  ok - motionFrameResample(${row.count}@${row.source_fps}fps) rejects: "${row.error.slice(0, 52)}…"`)
      continue
    }
    const plan = lib.motionFrameResample(row.count, row.source_fps)
    if (row.indices) {
      eq(plan.indices, row.indices, `motionFrameResample(${row.count}@${row.source_fps}) indices`)
      assert.strictEqual(plan.target, row.target_unaligned, 'target unaligned matches')
      passed += 1
      console.log(`  ok - motionFrameResample(${row.count}@${row.source_fps}fps): target ${row.target_unaligned} -> ${plan.aligned}`)
    } else {
      assert.strictEqual(plan.aligned, row.target_count, `motionFrameResample(${row.count}@${row.source_fps}) aligned`)
      passed += 1
      console.log(`  ok - motionFrameResample(${row.count}@${row.source_fps}fps) -> ${plan.aligned}`)
    }
    // (R1, central-model audit) the reference truncation reads the LEDGER's
    // named down-policy — the port's grid arithmetic is the same one home as
    // the video factory's snap-up, never a second grid.
    assert.strictEqual(plan.aligned, semantics.h3TruncateToGridDown(plan.target),
      `motionFrameResample(${row.count}@${row.source_fps}) aligned ≡ the ledger's truncate-down`)
  }
  for (const row of FIXTURE.resample) {
    if (!row.mode) continue
    const attempt = () => {
      if (row.mode === 'motion_vs_task') {
        lib.compileMotion({
          cameraTrajectory: pathJson('direita_90'), profile: '124 frames (~5.17s)', interpolation: 'smooth',
          instruction: '', runtimeTask: 'directed | new camera angle', frameMode: 'Motion Frame',
        })
      } else if (row.mode === 'missing_seq') {
        return lib.compileMotion({
          cameraTrajectory: pathJson('direita_90'), profile: '124 frames (~5.17s)', interpolation: 'smooth',
          instruction: '', frameMode: 'Motion Frame', referenceImage: null,
        })
      } else {
        const shape = row.mode === 'bad_shape' ? { shape: [2, 4, 5] } : { shape: [5, 1080, 1920, 3] }
        return lib.compileMotion({
          cameraTrajectory: pathJson('direita_90'), profile: '124 frames (~5.17s)', interpolation: 'smooth',
          instruction: '', frameMode: row.mode === 'freeze' || row.mode === 'freeze_oob' ? 'Freeze Frame' : 'Motion Frame',
          referenceImage: shape,
          sourceFps: row.source_fps,
          freezeIndex: row.mode === 'freeze' ? 4 : 9,
        })
      }
    }
    if (row.mode === 'freeze') {
      const frozen = attempt()
      assert.ok(frozen && frozen.resample === null, 'freeze mode picks one frame and does not resample')
      passed += 1
      console.log('  ok - freeze mode picks the single selected frame without resampling')
      continue
    }
    assert.throws(attempt, (err) => err.message === row.error, `${row.mode} message mismatch`)
    passed += 1
    console.log(`  ok - ${row.mode}: "${row.error.slice(0, 60)}…"`)
  }
  for (const row of FIXTURE.resample) {
    if (row.mode || !row.error) continue
    assert.throws(() => lib.motionFrameResample(row.count, row.source_fps), (err) => err.message === row.error,
      `motionFrameResample(${row.count}@${row.source_fps}) error mismatch`)
    passed += 1
    console.log(`  ok - motionFrameResample(${row.count}@${row.source_fps}fps) rejects: "${row.error.slice(0, 52)}…"`)
  }
})

test('(j) coordinateAnchor', () => {
  eq(lib.coordinateAnchor(''), {
    kind: 'reference_image',
    box: '[L=0.000, T=0.000, W=1.000, H=1.000]',
    instruction: 'The complete reference image occupies [L=0.000, T=0.000, W=1.000, H=1.000]. Preserve its initial composition. This is the image boundary, not a subject bounding box.',
  }, 'empty subject_box anchors the full image boundary')
  const anchor = lib.coordinateAnchor('[L=0.5160, T=0.148, W=0.071, H=0.249]')
  same(anchor.box, '[L=0.5160, T=0.148, W=0.071, H=0.249]', 'supplied precision preserved verbatim')
  same(lib.coordinateAnchor('[L=5.16e-1, T=.148, W=0.071, H=0.249]').box, '[L=5.16e-1, T=.148, W=0.071, H=0.249]', 'exponent and bare-dot syntax preserved')
  assert.throws(() => lib.coordinateAnchor('L=0.1'), (e) => e.message === 'subject_box must use [L=0.516, T=0.148, W=0.071, H=0.249], or be empty.', 'format message')
  passed += 1
  console.log('  ok - malformed box rejected with the upstream message')
  assert.throws(() => lib.coordinateAnchor('[L=0.9, T=0.1, W=0.3, H=0.2]'), (e) => e.message === 'subject_box must have positive size and stay within the normalized image.', 'bounds message')
  passed += 1
  console.log('  ok - box outside the frame rejected with the upstream message')
  // Upstream strips before matching, so surrounding whitespace is accepted —
  // Python's re.fullmatch never sees it (the m[0] guard in the port keeps the
  // same property had the strip not been there).
  ok(lib.coordinateAnchor('[L=0.1, T=0.1, W=0.2, H=0.2]\n').box === '[L=0.1, T=0.1, W=0.2, H=0.2]',
    'surrounding whitespace stripped before matching, like str.strip() upstream')
  assert.throws(() => lib.coordinateAnchor('[L=-0.1, T=0.1, W=0.2, H=0.2]'), (e) => e.message === 'subject_box must have positive size and stay within the normalized image.', 'negative L')
  passed += 1
  console.log('  ok - negative L rejected')
  console.log('')
  console.log(`camera suite: ${passed} assertions passed`)
})

function pathFromName(name) {
  const table = {
    direita_90: [
      { time: 0, azimuth: 0, elevation: 0, distance: 1 },
      { time: 1, azimuth: 90, elevation: 0, distance: 1 },
    ],
    esquerda_90: [
      { time: 0, azimuth: 0, elevation: 0, distance: 1 },
      { time: 1, azimuth: -90, elevation: 0, distance: 1 },
    ],
    video_00063: [
      { time: 0, azimuth: 0, elevation: 0, distance: 1 },
      { time: 0.5, azimuth: 38, elevation: 10, distance: 1 },
      { time: 1, azimuth: 90, elevation: 0, distance: 0.8 },
    ],
    loop_circle: [
      { time: 0, azimuth: 0, elevation: 0, distance: 1 },
      { time: 0.5, azimuth: 180, elevation: 8, distance: 1.2 },
      { time: 1, azimuth: 360, elevation: 0, distance: 1 },
    ],
    reversal_hold: [
      { time: 0, azimuth: 0, elevation: 0, distance: 1 },
      { time: 0.15, azimuth: 0, elevation: 0, distance: 1 },
      { time: 0.5, azimuth: 40, elevation: 6, distance: 1 },
      { time: 0.75, azimuth: 40, elevation: 6, distance: 1 },
      { time: 1, azimuth: -30, elevation: 0, distance: 0.9 },
    ],
    push_in: [
      { time: 0, azimuth: 0, elevation: 0, distance: 1 },
      { time: 1, azimuth: 0, elevation: 12, distance: 0.45 },
    ],
    slope: [
      { time: 0, azimuth: 0, elevation: 0, distance: 1 },
      { time: 0.3, azimuth: 100, elevation: 10, distance: 1.5 },
      { time: 0.7, azimuth: -40, elevation: -10, distance: 0.8 },
      { time: 1, azimuth: 20, elevation: 4, distance: 1 },
    ],
    static: [
      { time: 0, azimuth: 0, elevation: 0, distance: 1 },
      { time: 0.4, azimuth: 0, elevation: 0, distance: 1 },
      { time: 1, azimuth: 0, elevation: 0, distance: 1 },
    ],
  }
  return table[name]
}

function pathJson(name) {
  return JSON.stringify(pathFromName(name))
}
